[project]
name = "sanbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.126.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "supervisor>=4.3.0",
    "uvicorn>=0.38.0",
]
