services:
  manus-sandbox-dev:
    build:
      context: ../
      dockerfile: .devops/Dockerfile
    # 将当前目录挂载到工作空间/workspace
    volumes:
      - ../:/workspace
    # 端口映射
    ports:
      - "2222:22" # 本地2222->容器SSH 22
      - "8080:8080" # 本地 8080->容器Sandbox 8080
    # 容器的名字
    container_name: manus_sandbox_dev
    # 碰到错误则自动重启
    restart: always